# OracleDB connection settings
spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
        driverClassName: oracle.jdbc.OracleDriver
        username: localdev
        password: localdev
        oracleucp.connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
        oracleucp.initial-pool-size: 5
        oracleucp.min-pool-size: 5
        oracleucp.max-pool-size: 10

# JPA settings
    jpa:
        database-platform: org.hibernate.dialect.Oracle12cDialect
        hibernate:
            use-new-id-generator-mappings: false
            ddl-auto: create    
    server:
        port: 8080
